linux: Fix build due to missing fold command from coreutils
Since linux-next 20181130, fold is necessary to build:

    | build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/scripts/atomic/atomic-tbl.sh: line 183: fold: command not found
    | In file included from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/arch/arm/include/asm/bitops.h:243:0,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/linux/bitops.h:19,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/linux/kernel.h:11,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/asm-generic/bug.h:18,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/arch/arm/include/asm/bug.h:60,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/linux/bug.h:5,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/linux/page-flags.h:10,
    |                  from build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/kernel/bounds.c:10:
    | build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/asm-generic/bitops/lock.h: In function 'test_and_set_bit_lock':
    | build/tmp/work-shared/col-vf50-proceq-mainline-next/kernel-source/include/asm-generic/bitops/lock.h:28:8: error: implicit declaration of function 'atomic_long_fetch_or_acquire' [-Werror=implicit-function-declaration]
    |   old = atomic_long_fetch_or_acquire(mask, (atomic_long_t *)p);
    |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>