build: conf: Remove distrodata as it is gone from Yocto
Since commit 739c420caa13 ("distrodata: Remove"), the distrodata is gone
in favor of tinfoil.

This fixes error on current master branch:

    ERROR: ParseError in configuration INHERITs: Could not inherit file classes/distrodata.bbclass

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>